name: PS-1
on:
  push:
    branches:
        - feature1
jobs:
    job-1: 
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: git clone
              uses: actions/checkout@v4
            - name: install dependencies
              run: npm ci
            - name: check linting
              run: npm run lint
            - name: run test
              run: npm test
            - name: build
              run: npm run build

